### ISSUE TITLE
support for a http proxy

### ISSUE THREAD

**Issue by mario-tux** [misery/DockerVirtlyst#1]
Hi, 
I'm using you docker image to run Virlyst but I faced an issue: I run it behind traefik and without the option `--using-frontend-proxy`. Could you add it to your `Dockerfile` if it doesn't interfere with the base deployment?

**Comment by misery** [comment]
Wow, the image is available since 2 days. That was fast that someone uses it. :slightly_smiling_face: 
Yeah, I added it to the Dockerfile.
