### ISSUE TITLE
console doesn't work

### ISSUE THREAD

**Issue by mario-tux** [misery/DockerVirtlyst#2]
Hi,
the main issue now is that the console (spice, vnc) doesn't work for me. Are you able to use it? It maybe related to the use of an http proxy (traefik for me) and, for sure, to the missing map of the web socket calls.
In the original configuration there is an option to fix the port: I tried to add an `--http-socket :3000` option. A tweak on the option of traefik could be necessary.

**Comment by misery** [comment]
Do you use it Virtlyst on same host or is it a remote session via ssh? Virtlyst cannot connect to 127.0.0.1 on another machine. It lacks to create a new ssh tunnel for that.
Looks like you mean the upstream bug: https://github.com/cutelyst/Virtlyst/issues/28

As work around you can enable "all interfaces with password" on the VM settings. That works for me. The better fix would be a separate tunnel. But that needs to be fixed upstream.

**Comment by mario-tux** [comment]
Yes, it is a remote server. The clean solution would be a second ssh tunnel, I agree.

**Comment by misery** [comment]
This works fine for me: https://github.com/cutelyst/Virtlyst/pull/44
I will wait for review before I add it to docker image.
